---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether jq is installed
      ansible.builtin.command: jq --version
      register: JQ_VERSION
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure jq is installed
      ansible.builtin.debug:
        var: JQ_VERSION

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
