---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether jq is installed
      command: jq --version
      environment:
        TERM: xterm
      register: JQ_VERSION
      changed_when: false

    - name: Check OS version
      command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show jq version
      debug:
        var: JQ_VERSION

    - name: Show OS version
      debug:
        var: OS_VERSION
